# Generated by Django 3.1.1 on 2020-10-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biznumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
