# Generated by Django 3.1.2 on 2020-10-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makeChatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('user_id', models.IntegerField(unique=True)),
                ('room_name', models.CharField(max_length=100, null=True)),
                ('usercount', models.IntegerField(default=1)),
            ],
        ),
    ]
