# Generated by Django 3.1.2 on 2020-10-05 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makechatroom',
            name='user_id',
        ),
        migrations.AddField(
            model_name='makechatroom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='makechatroom',
            name='usercount',
            field=models.IntegerField(default=0),
        ),
    ]
