# Generated by Django 3.1.1 on 2020-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.IntegerField()),
                ('userid', models.IntegerField(null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('content', models.TextField(null=True)),
                ('reg_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
