# Generated by Django 3.1.1 on 2020-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('store_name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('start_time', models.CharField(max_length=20, null=True)),
                ('end_time', models.CharField(max_length=20, null=True)),
                ('min_price', models.IntegerField(null=True)),
                ('mon', models.IntegerField(null=True)),
                ('tue', models.IntegerField(null=True)),
                ('wed', models.IntegerField(null=True)),
                ('thu', models.IntegerField(null=True)),
                ('fri', models.IntegerField(null=True)),
                ('sat', models.IntegerField(null=True)),
                ('sun', models.IntegerField(null=True)),
            ],
        ),
    ]
